cc_library(
    name = "pong",
    srcs = [
        "Action.C",
        "Environment.C",
        "Game.C",
        "Manager.C",
        "Reward.C",
        "State.C",
    ],
    hdrs = [
        "Action.H",
        "Agent.H",
        "Environment.H",
        "Game.H",
        "Manager.H",
        "Reward.H",
        "State.H",
    ],
    copts = [
        "-std=c++14",
        "-fext-numeric-literals",
        "-Wfatal-errors",
    ],
)
