cc_library(
    name = "agents",
    visibility = ["//visibility:public"],
    srcs = [
        "Human.C",
        "Intuitive.C",
        "MonteCarlo.C",
    ],
    hdrs = [
        "Human.H",
        "Intuitive.H",
        "MonteCarlo.H",
    ],
    deps = [
        "//pong:pong",
    ],
)
