cc_library(
    name = "pong",
    srcs = [
        "pong/Action.C",
        "pong/Environment.C",
        "pong/Game.C",
        "pong/Manager.C",
        "pong/Reward.C",
        "pong/State.C",
    ],

